### ISSUE TITLE
arduino compile error message

### ISSUE THREAD

**Issue by m0userat25** [jvoigts/2p_opto#1]
Hello Jakob,

I get the following error message when I compile your arduino code. I am currently using an Arduino Uno. Is it meant only for the Leonardo?

Thanks so much in advance.

Abhishek

Arduino: 1.8.2 (Mac OS X), Board: "Arduino/Genuino Uno"

pulse_led_2p_opto:23: error: stray '\302' in program
   <title> 2p_opto/pulse_led_2p_opto.ino at master · jvoigts/2p_opto · GitHub </title>
   ^
pulse_led_2p_opto:23: error: stray '\267' in program
pulse_led_2p_opto:23: error: stray '\302' in program
pulse_led_2p_opto:23: error: stray '\267' in program
/Users/abhishek/Downloads/pulse_led_2p_opto/pulse_led_2p_opto.ino:130:8: warning: missing terminating ' character
   </option></form><form accept-charset="UTF-8" action="/jvoigts/2p_opto/search" class="js-site-search-form" data-scoped-search-url="/jvoigts/2p_opto/search" data-unscoped-search-url="/search" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
        ^
pulse_led_2p_opto:130: error: missing terminating ' character
   </option></form><form accept-charset="UTF-8" action="/jvoigts/2p_opto/search" class="js-site-search-form" data-scoped-search-url="/jvoigts/2p_opto/search" data-unscoped-search-url="/search" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
   ^
/Users/abhishek/Downloads/pulse_led_2p_opto/pulse_led_2p_opto.ino:701:8: warning: missing terminating ' character
   </option></form><form accept-charset="UTF-8" action="" class="js-jump-to-line-form" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
        ^
pulse_led_2p_opto:701: error: missing terminating ' character
   </option></form><form accept-charset="UTF-8" action="" class="js-jump-to-line-form" method="get"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
   ^
/Users/abhishek/Downloads/pulse_led_2p_opto/pulse_led_2p_opto.ino:751:12: warning: missing terminating ' character
     You can't perform that action at this time.
            ^
pulse_led_2p_opto:751: error: missing terminating ' character
     You can't perform that action at this time.
     ^
pulse_led_2p_opto:7: error: expected unqualified-id before '<' token
 <!DOCTYPE html>
 ^
pulse_led_2p_opto:477: error: expected unqualified-id before '<' token
         <td id="LC8" class="blob-code blob-code-inner js-file-line"><span class="pl-k">const</span> <span class="pl-k">int</span> ledPin =  <span class="pl-c1">4</span>;      <span class="pl-c"><span class="pl-c">//</span> LED pin</span></td>
                                                                                                                                                                                ^
pulse_led_2p_opto:481: error: expected unqualified-id before '<' token
         <td id="LC9" class="blob-code blob-code-inner js-file-line"><span class="pl-k">const</span> <span class="pl-k">int</span> trigPin = <span class="pl-c1">2</span>; <span class="pl-c"><span class="pl-c">//</span> look for trigger input here, not needed if output is used to gate an existing LED driver signal (with an analog max circuit or similar method)</span></td>
                                                                                                                                                                           ^
pulse_led_2p_opto:490: error: expected unqualified-id before '<' token
         <td id="LC11" class="blob-code blob-code-inner js-file-line"><span class="pl-k">const</span> <span class="pl-k">int</span> controlPin = <span class="pl-c1">12</span>; <span class="pl-c"><span class="pl-c">//</span> look for frame trigger input here</span></td>
                                                                                                                                                                                ^
pulse_led_2p_opto:499: error: expected unqualified-id before '<' token
         <td id="LC13" class="blob-code blob-code-inner js-file-line"><span class="pl-k">int</span> armed = LOW;                    <span class="pl-c"><span class="pl-c">//</span> ledState used to set the LED</span></td>
                                                                                                                                    ^
pulse_led_2p_opto:503: error: expected unqualified-id before '<' token
         <td id="LC14" class="blob-code blob-code-inner js-file-line"><span class="pl-k">unsigned</span> <span class="pl-k">long</span> endMicros = <span class="pl-c1">0</span>;        <span class="pl-c"><span class="pl-c">//</span> will store last time LED was updated</span></td>
                                                                                                                                                                                         ^
pulse_led_2p_opto:507: error: expected unqualified-id before '<' token
         <td id="LC15" class="blob-code blob-code-inner js-file-line"><span class="pl-k">int</span> prevtrig = LOW;</td>
                                                                                                                   ^
pulse_led_2p_opto:516: error: expected unqualified-id before '<' token
         <td id="LC17" class="blob-code blob-code-inner js-file-line"><span class="pl-k">int</span> line = <span class="pl-c1">0</span>;                      <span class="pl-c"><span class="pl-c">//</span> keep track of what image scan line we&#39;re on</span></td>
                                                                                                                                                              ^
pulse_led_2p_opto:520: error: expected unqualified-id before '<' token
         <td id="LC18" class="blob-code blob-code-inner js-file-line"><span class="pl-k">int</span> skiplines = <span class="pl-c1">8</span>;</td>
                                                                                                                                             ^
pulse_led_2p_opto:534: error: expected unqualified-id before '<' token
         <td id="LC21" class="blob-code blob-code-inner js-file-line"><span class="pl-k">unsigned</span> <span class="pl-k">long</span> wait = <span class="pl-c1">0</span>;           <span class="pl-c"><span class="pl-c">//</span> target interval between end of scanlne and light pulse (actual nu,bers will be ~50-100us higher - measure with oscilloscope)</span></td>
                                                                                                                                                                                       ^
pulse_led_2p_opto:538: error: expected unqualified-id before '<' token
         <td id="LC22" class="blob-code blob-code-inner js-file-line"><span class="pl-k">unsigned</span> <span class="pl-k">long</span> duration = <span class="pl-c1">100</span>;    <span class="pl-c"><span class="pl-c">//</span> approx pulse duration - won&#39;t be precise for all values but should be consistent across pulses</span></td>
                                                                                                                                                                                      ^
pulse_led_2p_opto:565: error: expected unqualified-id before '<' token
         <td id="LC28" class="blob-code blob-code-inner js-file-line">}</td>
                                                                       ^
exit status 1
stray '\302' in program

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jvoigts** [comment]
this sounds like a encoding issue, like in the line endings- can you try changing the encoding?

**Comment by m0userat25** [comment]
thanks. i tried using the fix encoding and reload function and that has not solved it. so i will try to change it myself.

**Comment by jvoigts** [comment]
Just checked- this seems to be an issue with non-ASCII chars. Maybe try just copy&pasting it, and/or open it in a text editor and get rid of non-ascii characters there? I can compile it just fine on ubuntu using a current arduino ide.

**Comment by m0userat25** [comment]
YES! copying and pasting did the trick. Thank you!
